//
// Generated by afu_json_mgr from ../../hw/rtl/dma_afu.json
//

#ifndef __AFU_JSON_INFO__
#define __AFU_JSON_INFO__

#define AFU_ACCEL_NAME "dma_afu"
#define AFU_ACCEL_UUID "8031BE25-0CF4-40EE-A411-DBAF7E894DF5"
#define AFU_IMAGE_POWER 0
#define AFU_TOP_IFC "ccip_std_afu"

#endif // __AFU_JSON_INFO__
