# TCL File Generated by Component Editor 17.1.1
# Mon Jun 25 21:00:49 CDT 2018
# DO NOT MODIFY


# 
# far_reach_avalon_mm_bridge "Far Reach Avalon-MM Bridge" v1.0
# JCJB 2018.06.25.21:00:49
# An Avalon-MM bridge with configuration number of pipeline stages
# 

# 
# request TCL package from ACDS 17.1
# 
package require -exact qsys 17.1


# 
# module far_reach_avalon_mm_bridge
# 
set_module_property DESCRIPTION "An Avalon-MM bridge with configuration number of pipeline stages"
set_module_property NAME far_reach_avalon_mm_bridge
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR JCJB
set_module_property DISPLAY_NAME "Far Reach Avalon-MM Bridge"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL far_reach_avalon_mm_bridge
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file far_reach_avalon_mm_bridge.sv SYSTEM_VERILOG PATH far_reach_avalon_mm_bridge.sv TOP_LEVEL_FILE
add_fileset_file far_reach_avalon_mm_bridge_stall_free_pipeline.sv SYSTEM_VERILOG PATH far_reach_avalon_mm_bridge_stall_free_pipeline.sv

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL far_reach_avalon_mm_bridge
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file far_reach_avalon_mm_bridge.sv SYSTEM_VERILOG PATH far_reach_avalon_mm_bridge.sv
add_fileset_file far_reach_avalon_mm_bridge_stall_free_pipeline.sv SYSTEM_VERILOG PATH far_reach_avalon_mm_bridge_stall_free_pipeline.sv

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL far_reach_avalon_mm_bridge
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file far_reach_avalon_mm_bridge.sv SYSTEM_VERILOG PATH far_reach_avalon_mm_bridge.sv
add_fileset_file far_reach_avalon_mm_bridge_stall_free_pipeline.sv SYSTEM_VERILOG PATH far_reach_avalon_mm_bridge_stall_free_pipeline.sv


set_module_property ELABORATION_CALLBACK elaborate_me
set_module_property VALIDATION_CALLBACK validate_me


# 
# parameters
# 
add_parameter DATA_WIDTH INTEGER 32
set_parameter_property DATA_WIDTH ALLOWED_RANGES {8 16 32 64 128 256 512 1024}
set_parameter_property DATA_WIDTH DISPLAY_NAME "Data Width"
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_display_item "Interface Options" DATA_WIDTH parameter

add_parameter ADDRESS_WIDTH INTEGER 32
set_parameter_property ADDRESS_WIDTH ALLOWED_RANGES {1:2B 2:4B 3:8B 4:16B 5:32B 6:64B 7:128B 8:256B 9:512B 10:1kB 11:2kB 12:4kB 13:8kB 14:16kB 15:32kB 16:64kB
                                                     17:128kB 18:256kB 19:512kB 20:1MB 21:2MB 22:4MB 23:8MB 24:16MB 25:32MB 26:64MB 27:128MB 28:256MB 29:512MB 30:1GB 31:2GB 32:4GB
                                                     33:8GB 34:16GB 35:32GB 36:64GB 37:128GB 38:256GB 39:512GB 40:1TB 41:2TB 42:4TB 43:8TB 44:16TB 45:32TB 46:64TB 47:128TB 48:256TB
                                                     49:512TB 50:1PB 51:2PB 52:4PB 53:8PB 54:16PB 55:32PB 56:64PB 57:128PB 58:256PB 59:512PB}
set_parameter_property ADDRESS_WIDTH DISPLAY_NAME "Address Span"
set_parameter_property ADDRESS_WIDTH UNITS None
set_parameter_property ADDRESS_WIDTH HDL_PARAMETER true
add_display_item "Interface Options" ADDRESS_WIDTH parameter

add_parameter BURST_COUNT INTEGER 1
set_parameter_property BURST_COUNT ALLOWED_RANGES {1 2 4 8 16 32 64 128}
set_parameter_property BURST_COUNT DISPLAY_NAME "Burst Count"
set_parameter_property BURST_COUNT UNITS None
set_parameter_property BURST_COUNT HDL_PARAMETER false
add_display_item "Interface Options" BURST_COUNT parameter

# will be calculated based on log2(BURST_COUNT) + 1 in the validation callback
add_parameter BURST_WIDTH INTEGER 1
set_parameter_property BURST_WIDTH DISPLAY_NAME BURST_WIDTH
set_parameter_property BURST_WIDTH UNITS None
set_parameter_property BURST_WIDTH HDL_PARAMETER true
set_parameter_property BURST_WIDTH DERIVED true
set_parameter_property BURST_WIDTH VISIBLE false

add_parameter RESPONSE_ENABLE INTEGER 0
set_parameter_property RESPONSE_ENABLE DISPLAY_NAME "Response Enable"
set_parameter_property RESPONSE_ENABLE UNITS None
set_parameter_property RESPONSE_ENABLE HDL_PARAMETER false
set_parameter_property RESPONSE_ENABLE DISPLAY_HINT boolean
add_display_item "Interface Options" RESPONSE_ENABLE parameter




add_parameter READ_ENABLE INTEGER 1
set_parameter_property READ_ENABLE DISPLAY_NAME "Read Enable"
set_parameter_property READ_ENABLE UNITS None
set_parameter_property READ_ENABLE HDL_PARAMETER false
set_parameter_property READ_ENABLE DISPLAY_HINT boolean
add_display_item "Read Options" READ_ENABLE parameter

add_parameter MAX_PENDING_READS INTEGER 64
set_parameter_property MAX_PENDING_READS ALLOWED_RANGES {4 8 16 32 64 128 256 512}
set_parameter_property MAX_PENDING_READS DISPLAY_NAME "Max Pending Reads"
set_parameter_property MAX_PENDING_READS UNITS None
set_parameter_property MAX_PENDING_READS HDL_PARAMETER true
add_display_item "Read Options" MAX_PENDING_READS parameter



add_parameter WRITE_ENABLE INTEGER 1
set_parameter_property WRITE_ENABLE DISPLAY_NAME "Write Enable"
set_parameter_property WRITE_ENABLE UNITS None
set_parameter_property WRITE_ENABLE HDL_PARAMETER false
set_parameter_property WRITE_ENABLE DISPLAY_HINT boolean
add_display_item "Write Options" WRITE_ENABLE parameter

add_parameter MAX_PENDING_WRITES INTEGER 64
set_parameter_property MAX_PENDING_WRITES ALLOWED_RANGES {4 8 16 32 64 128 256 512}
set_parameter_property MAX_PENDING_WRITES DISPLAY_NAME "Max Pending Writes"
set_parameter_property MAX_PENDING_WRITES UNITS None
set_parameter_property MAX_PENDING_WRITES HDL_PARAMETER true
add_display_item "Write Options" MAX_PENDING_Writes parameter

add_parameter WRITE_TRACKING_ENABLE INTEGER 1
set_parameter_property WRITE_TRACKING_ENABLE DISPLAY_NAME WRITE_TRACKING_ENABLE
set_parameter_property WRITE_TRACKING_ENABLE UNITS None
set_parameter_property WRITE_TRACKING_ENABLE HDL_PARAMETER true
set_parameter_property WRITE_TRACKING_ENABLE DERIVED true
set_parameter_property WRITE_TRACKING_ENABLE VISIBLE false



add_parameter DOWNSTREAM_PIPELINE_STAGES INTEGER 1
set_parameter_property DOWNSTREAM_PIPELINE_STAGES ALLOWED_RANGES {1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16}
set_parameter_property DOWNSTREAM_PIPELINE_STAGES DISPLAY_NAME "Command Pipeline Depth"
set_parameter_property DOWNSTREAM_PIPELINE_STAGES UNITS None
set_parameter_property DOWNSTREAM_PIPELINE_STAGES HDL_PARAMETER true
add_display_item "Pipeline Options" DOWNSTREAM_PIPELINE_STAGES parameter

add_parameter WAITREQUEST_PIPELINE_STAGES INTEGER 1
set_parameter_property WAITREQUEST_PIPELINE_STAGES ALLOWED_RANGES {1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16}
set_parameter_property WAITREQUEST_PIPELINE_STAGES DISPLAY_NAME "Waitrequest Pipeine Depth"
set_parameter_property WAITREQUEST_PIPELINE_STAGES UNITS None
set_parameter_property WAITREQUEST_PIPELINE_STAGES HDL_PARAMETER true
add_display_item "Pipeline Options" WAITREQUEST_PIPELINE_STAGES parameter

add_parameter UPSTREAM_PIPELINE_STAGES INTEGER 1
set_parameter_property UPSTREAM_PIPELINE_STAGES ALLOWED_RANGES {1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16}
set_parameter_property UPSTREAM_PIPELINE_STAGES DISPLAY_NAME "Response Pipeline Depth"
set_parameter_property UPSTREAM_PIPELINE_STAGES UNITS None
set_parameter_property UPSTREAM_PIPELINE_STAGES HDL_PARAMETER true
add_display_item "Pipeline Options" UPSTREAM_PIPELINE_STAGES parameter





# none of the parameters below should be presented to user
add_parameter SKID_FIFO_DEPTH INTEGER 32
set_parameter_property SKID_FIFO_DEPTH DISPLAY_NAME SKID_FIFO_DEPTH
set_parameter_property SKID_FIFO_DEPTH UNITS None
set_parameter_property SKID_FIFO_DEPTH HDL_PARAMETER true
set_parameter_property SKID_FIFO_DEPTH VISIBLE false
set_parameter_property SKID_FIFO_DEPTH DERIVED true

add_parameter SKID_FIFO_ALMOST_FULL_LEVEL INTEGER 10
set_parameter_property SKID_FIFO_ALMOST_FULL_LEVEL DISPLAY_NAME SKID_FIFO_ALMOST_FULL_LEVEL
set_parameter_property SKID_FIFO_ALMOST_FULL_LEVEL UNITS None
set_parameter_property SKID_FIFO_ALMOST_FULL_LEVEL HDL_PARAMETER true
set_parameter_property SKID_FIFO_ALMOST_FULL_LEVEL VISIBLE false
set_parameter_property SKID_FIFO_ALMOST_FULL_LEVEL DERIVED true


# none of the parameters below are used yet
add_parameter SKID_FIFO_CLOCK_CROSSING_ENABLE INTEGER 0
set_parameter_property SKID_FIFO_CLOCK_CROSSING_ENABLE DISPLAY_NAME SKID_FIFO_CLOCK_CROSSING_ENABLE
set_parameter_property SKID_FIFO_CLOCK_CROSSING_ENABLE UNITS None
set_parameter_property SKID_FIFO_CLOCK_CROSSING_ENABLE HDL_PARAMETER true
set_parameter_property SKID_FIFO_CLOCK_CROSSING_ENABLE VISIBLE false

add_parameter UPSTREAM_CLOCK_CROSSING_ENABLE INTEGER 0
set_parameter_property UPSTREAM_CLOCK_CROSSING_ENABLE DEFAULT_VALUE 0
set_parameter_property UPSTREAM_CLOCK_CROSSING_ENABLE DISPLAY_NAME UPSTREAM_CLOCK_CROSSING_ENABLE
set_parameter_property UPSTREAM_CLOCK_CROSSING_ENABLE UNITS None
set_parameter_property UPSTREAM_CLOCK_CROSSING_ENABLE HDL_PARAMETER true
set_parameter_property UPSTREAM_CLOCK_CROSSING_ENABLE VISIBLE false

add_parameter UPSTREAM_FIFO_DEPTH INTEGER 32
set_parameter_property UPSTREAM_FIFO_DEPTH DEFAULT_VALUE 32
set_parameter_property UPSTREAM_FIFO_DEPTH DISPLAY_NAME UPSTREAM_FIFO_DEPTH
set_parameter_property UPSTREAM_FIFO_DEPTH UNITS None
set_parameter_property UPSTREAM_FIFO_DEPTH HDL_PARAMETER true
set_parameter_property UPSTREAM_FIFO_DEPTH VISIBLE false

add_parameter UPSTREAM_FIFO_ALMOST_FULL_LEVEL INTEGER 10
set_parameter_property UPSTREAM_FIFO_ALMOST_FULL_LEVEL DEFAULT_VALUE 10
set_parameter_property UPSTREAM_FIFO_ALMOST_FULL_LEVEL DISPLAY_NAME UPSTREAM_FIFO_ALMOST_FULL_LEVEL
set_parameter_property UPSTREAM_FIFO_ALMOST_FULL_LEVEL UNITS None
set_parameter_property UPSTREAM_FIFO_ALMOST_FULL_LEVEL HDL_PARAMETER true
set_parameter_property UPSTREAM_FIFO_ALMOST_FULL_LEVEL VISIBLE false


# 
# display items
# 



# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk s_clk clk Input 1


# 
# connection point master_clk
# 
add_interface master_clk clock end
set_interface_property master_clk clockRate 0
set_interface_property master_clk ENABLED true
set_interface_property master_clk EXPORT_OF ""
set_interface_property master_clk PORT_NAME_MAP ""
set_interface_property master_clk CMSIS_SVD_VARIABLES ""
set_interface_property master_clk SVD_ADDRESS_GROUP ""

add_interface_port master_clk m_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges BOTH
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1



# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressGroup 0
set_interface_property slave addressUnits SYMBOLS
set_interface_property slave associatedClock clk
set_interface_property slave associatedReset reset
set_interface_property slave bitsPerSymbol 8
set_interface_property slave bridgedAddressOffset ""
set_interface_property slave bridgesToMaster "master"
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave minimumResponseLatency 1
set_interface_property slave readLatency 0
set_interface_property slave readWaitTime 1
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave transparentBridge false
set_interface_property slave waitrequestAllowance 0
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave s_address address Input "((ADDRESS_WIDTH - 1)) - (0) + 1"
add_interface_port slave s_writedata writedata Input "((DATA_WIDTH - 1)) - (0) + 1"
add_interface_port slave s_byteenable byteenable Input "(((DATA_WIDTH / 8) - 1)) - (0) + 1"
add_interface_port slave s_write write Input 1
add_interface_port slave s_read read Input 1
add_interface_port slave s_readdata readdata Output "((DATA_WIDTH - 1)) - (0) + 1"
add_interface_port slave s_readdatavalid readdatavalid Output 1
add_interface_port slave s_response response Output 2
add_interface_port slave s_writeresponsevalid writeresponsevalid Output 1
add_interface_port slave s_waitrequest waitrequest Output 1
add_interface_port slave s_burst burstcount Input "((BURST_WIDTH - 1)) - (0) + 1"
set_interface_assignment slave embeddedsw.configuration.isFlash 0
set_interface_assignment slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point master
# 
add_interface master avalon start
set_interface_property master addressGroup 0
set_interface_property master addressUnits SYMBOLS
set_interface_property master associatedClock clk
set_interface_property master associatedReset reset
set_interface_property master bitsPerSymbol 8
set_interface_property master burstOnBurstBoundariesOnly false
set_interface_property master burstcountUnits WORDS
set_interface_property master doStreamReads false
set_interface_property master doStreamWrites false
set_interface_property master holdTime 0
set_interface_property master linewrapBursts false
set_interface_property master minimumResponseLatency 1
set_interface_property master readLatency 0
set_interface_property master readWaitTime 1
set_interface_property master setupTime 0
set_interface_property master timingUnits Cycles
set_interface_property master waitrequestAllowance 0
set_interface_property master writeWaitTime 0
set_interface_property master ENABLED true
set_interface_property master EXPORT_OF ""
set_interface_property master PORT_NAME_MAP ""
set_interface_property master CMSIS_SVD_VARIABLES ""
set_interface_property master SVD_ADDRESS_GROUP ""

add_interface_port master m_address address Output "((ADDRESS_WIDTH - 1)) - (0) + 1"
add_interface_port master m_writedata writedata Output "((DATA_WIDTH - 1)) - (0) + 1"
add_interface_port master m_byteenable byteenable Output "(((DATA_WIDTH / 8) - 1)) - (0) + 1"
add_interface_port master m_burst burstcount Output "((BURST_WIDTH - 1)) - (0) + 1"
add_interface_port master m_write write Output 1
add_interface_port master m_read read Output 1
add_interface_port master m_readdata readdata Input "((DATA_WIDTH - 1)) - (0) + 1"
add_interface_port master m_readdatavalid readdatavalid Input 1
add_interface_port master m_response response Input 2
add_interface_port master m_writeresponsevalid writeresponsevalid Input 1
add_interface_port master m_waitrequest waitrequest Input 1



proc elaborate_me {}  { 
  
  # do not support clock crossing for now
  set_port_property m_clk TERMINATION true
  set_interface_property master_clk ENABLED false   

  # optional read port stuff
  if  { [get_parameter_value READ_ENABLE] == 1 }  {
    set_interface_property master maximumPendingReadTransactions [get_parameter_value MAX_PENDING_READS]
    set_interface_property slave maximumPendingReadTransactions [get_parameter_value MAX_PENDING_READS]
    set_port_property s_read TERMINATION false
    set_port_property m_read TERMINATION false
    set_port_property s_readdata TERMINATION false
    set_port_property m_readdata TERMINATION false
    set_port_property s_readdatavalid TERMINATION false
    set_port_property m_readdatavalid TERMINATION false
  } else {
    set_interface_property master maximumPendingReadTransactions 0
    set_interface_property slave maximumPendingReadTransactions 0 
    set_port_property s_read TERMINATION true
    set_port_property m_read TERMINATION true
    set_port_property s_readdata TERMINATION true
    set_port_property m_readdata TERMINATION true
    set_port_property s_readdatavalid TERMINATION true
    set_port_property m_readdatavalid TERMINATION true
  }


  # optional write port stuff
  if  { [get_parameter_value WRITE_ENABLE] == 1 }  {
    if { [get_parameter_value WRITE_TRACKING_ENABLE] == 1}  {
      set_interface_property master maximumPendingWriteTransactions [get_parameter_value MAX_PENDING_WRITES]
      set_interface_property slave maximumPendingWriteTransactions [get_parameter_value MAX_PENDING_WRITES]
      set_port_property s_writeresponsevalid TERMINATION false
      set_port_property m_writeresponsevalid TERMINATION false
    } else {
      set_interface_property master maximumPendingWriteTransactions 0
      set_interface_property slave maximumPendingWriteTransactions 0 
      set_port_property s_writeresponsevalid TERMINATION true
      set_port_property m_writeresponsevalid TERMINATION true
    }
    set_port_property s_write TERMINATION false
    set_port_property m_write TERMINATION false
    set_port_property s_writedata TERMINATION false
    set_port_property m_writedata TERMINATION false
  } else {
    set_interface_property master maximumPendingWriteTransactions 0
    set_interface_property slave maximumPendingWriteTransactions 0 
    set_port_property s_write TERMINATION true
    set_port_property m_write TERMINATION true
    set_port_property s_writedata TERMINATION true
    set_port_property m_writedata TERMINATION true
    set_port_property s_writeresponsevalid TERMINATION true
    set_port_property m_writeresponsevalid TERMINATION true    
  } 

  
  # optional response tracking stuff (handling the writeresponsevalid signals in the write port section above
  if { [get_parameter_value RESPONSE_ENABLE] == 1}  {
    set_port_property s_response TERMINATION false
    set_port_property m_response TERMINATION false
  } else {
    set_port_property s_response TERMINATION true
    set_port_property m_response TERMINATION true
  }
  
}



proc validate_me {} { 

  if { ( [get_parameter_value WRITE_ENABLE] == 0 ) && ( [get_parameter_value READ_ENABLE] == 0 ) }   {
    send_message Error "You must enable reads or writes (or both)."
  }
  
  if { ( [get_parameter_value WRITE_ENABLE] == 1 ) && ( [get_parameter_value RESPONSE_ENABLE] == 1) }  {
    set_parameter_value WRITE_TRACKING_ENABLE 1
  } else {
    set_parameter_value WRITE_TRACKING_ENABLE 0
  }
  
  if { [get_parameter_value WRITE_TRACKING_ENABLE] == 1 }  {
    set_parameter_property MAX_PENDING_WRITES ENABLED true 
  } else {
    set_parameter_property MAX_PENDING_WRITES ENABLED false
  }
  
  if { [get_parameter_value READ_ENABLE] == 1 }  {
    set_parameter_property MAX_PENDING_READS ENABLED true 
  } else {
    set_parameter_property MAX_PENDING_READS ENABLED false
  }
  
  if { ( [get_parameter_value READ_ENABLE] == 1 ) || ( [get_parameter_value RESPONSE_ENABLE] == 1) }  {
    set_parameter_property UPSTREAM_PIPELINE_STAGES ENABLED true
  } else {
    set_parameter_property UPSTREAM_PIPELINE_STAGES ENABLED false
  }  
  
  # skid FIFO depth will be the total of (command pipeline stages + waitrequest stages) times 4 and rounded up to the nearest power of 2 (to make efficient use of the RAM blocks)
  set sum [ expr {[get_parameter_value DOWNSTREAM_PIPELINE_STAGES] + [get_parameter_value WAITREQUEST_PIPELINE_STAGES]} ]
  set sum4x [ expr {$sum * 4} ]
  set sum4xlog2 [ expr { log ($sum4x) / log (2) } ]
  set skid_fifo_depth [ expr {pow(2, ceil ($sum4xlog2)) } ]
  set_parameter_value SKID_FIFO_DEPTH $skid_fifo_depth
  # skid FIFO almost full threshold set to total round trip pipeline latency + 1
  set skid_fifo_almost_full_level [ expr {$skid_fifo_depth - $sum - 1} ] 
  set_parameter_value SKID_FIFO_ALMOST_FULL_LEVEL $skid_fifo_almost_full_level

  if { [get_parameter_value READ_ENABLE] == 1 }  {
    if { [get_parameter_value MAX_PENDING_READS] < [get_parameter_value DOWNSTREAM_PIPELINE_STAGES] }  {
      send_message Info "Note that the maximum pending reads setting is not set high enough to negate effects of command pipeline depth latency.  Throughput will be reduced as a result."
    }
  }

  if { ([get_parameter_value WRITE_ENABLE] == 1) && ([get_parameter_value RESPONSE_ENABLE] == 1) }  {
    if { [get_parameter_value MAX_PENDING_WRITES] < [get_parameter_value DOWNSTREAM_PIPELINE_STAGES] }  {
      send_message Info "Note that the maximum pending writes setting is not set high enough to negate effects of command pipeline depth latency.  Throughput will be reduced as a result."
    }
  }

  # if data width * 2 [bytes] > address span [bytes] then tell user to increase the address span 
  set data_width_bytes_x2 [expr {([get_parameter_value DATA_WIDTH] / 8) * 2 } ]
  set address_span [expr {pow(2, [get_parameter_value ADDRESS_WIDTH])} ]
  if { $data_width_bytes_x2 > $address_span }  {
    send_message ERROR "The address span is set too slow, set it to span at least $data_width_bytes_x2 bytes."
  } 

  set burstcountlog2 [expr { log([get_parameter_value BURST_COUNT]) / log(2) } ]
  set_parameter_value BURST_WIDTH [ expr { $burstcountlog2 + 1 } ]   
  
}




