alt_up_driver_codes: alt_up_pci_sdma.c File Reference
alt_up_pci_sdma.c File Reference
The source file for the simple DMA controller functions.
#include "alt_up_pci_sdma.h"
Functions
static void alt_up_pci_sdma_set (struct alt_up_dma_ctrller *myctrller, u32 local_addr, u32 phys_addr, u32 length, int to_device)
The function to set the DMA controller.
static void alt_up_pci_sdma_clear (struct alt_up_dma_ctrller *myctrller)
The function to clear registers of DMA controller.
static int alt_up_pci_sdma_polling (struct alt_up_dma_ctrller *myctrller)
The function to poll the result.
static int alt_up_pci_sdma_interrupt (struct alt_up_dma_ctrller *myctrller)
The function to use interrupt.
int alt_up_pci_sdma_init (struct alt_up_dma_ctrller *myctrller, int transfer_data_width)
The function to initialize the DMA controller.
void alt_up_pci_sdma_exit (struct alt_up_dma_ctrller *myctrller)
The function is called when the DMA controller is no longer used.
int alt_up_pci_sdma_go (struct alt_up_dma_ctrller *myctrller, int use_interrupt)
The function to set go for DMA transfers.
void alt_up_pci_sdma_swreset (struct alt_up_dma_ctrller *myctrller)
The function to do the software reset.
Detailed Description
The source file for the simple DMA controller functions.
The implementation of the funtions in this file is very basic and they are intended to provide and example of how to use the DMA controller. You will have to change them to improve the performance or satisfy your own need.
Definition in file alt_up_pci_sdma.c.
Function Documentation
static void alt_up_pci_sdma_clear (struct alt_up_dma_ctrller * myctrller) [inline, static]
The function to clear registers of DMA controller.
This function clear the status and control registers after the DMA transfer finished. The interrupt signal should be also cleared by this function.
Parameters:
[in] myctrller The DMA controller selected
Definition at line 268 of file alt_up_pci_sdma.c.
References alt_up_dma_ctrller::dma_ctrl_base_addr.
Referenced by alt_up_pci_sdma_go(), and alt_up_pci_sdma_init().
void alt_up_pci_sdma_exit (struct alt_up_dma_ctrller * myctrller)
The function is called when the DMA controller is no longer used.
This function will free all the memory allocated in alt_up_pci_sdma_init(). The function is called in alt_up_pci_dev_exit().
Parameters:
[in] myctrller The DMA controller selected
Definition at line 87 of file alt_up_pci_sdma.c.
References sdma::bus_addr, alt_up_dma_ctrller::pci_dev, alt_up_dma_ctrller::private_data, SDMA_BUF_SIZE, and sdma::virt_addr.
Referenced by alt_up_pci_dev_exit().
int alt_up_pci_sdma_go (struct alt_up_dma_ctrller * myctrller, int use_interrupt)
The function to set go for DMA transfers.
This function will do all the transcations in the dma_queue. If the transfer size is larger than the SDMA_BUF_SIZE, it will automatically divide the transfer into multiple tranfers.
Parameters:
[in] myctrller The DMA controller selected
[in] use_interrupt if 1, set the DMA controller to assert irq signal
Returns:
Returns 0 on success, -1 otherwise
Definition at line 106 of file alt_up_pci_sdma.c.
References alt_up_pci_sdma_clear(), alt_up_pci_sdma_interrupt(), alt_up_pci_sdma_polling(), alt_up_pci_sdma_set(), alt_up_pci_sdma_swreset(), sdma::bus_addr, sdma::data_width_in_bytes, alt_up_dma_ctrller::dma_ctrl_base_addr, sdma::dma_data_bit_mask, alt_up_dma_ctrller::dma_queue, alt_up_pci_dma::dma_rw_slave_addr, alt_up_pci_dma::length, alt_up_dma_ctrller::private_data, alt_up_dma_ctrller::queue_end, SDMA_BUF_SIZE, alt_up_pci_dma::to_device, alt_up_pci_dma::user_buffer_addr, and sdma::virt_addr.
Referenced by alt_up_pci_ioctl().
int alt_up_pci_sdma_init (struct alt_up_dma_ctrller * myctrller, int transfer_data_width)
The function to initialize the DMA controller.
This function allocates buffer for the DMA controller to transfer data, initialize necessary data, and clear the registers for dma controller.
Parameters:
[in] myctrller pointer to struct alt_up_dma_ctrller which points to the dma controller needed to be initialized
[in] transfer_data_width data width setting for the dma controller
Returns:
Returns 0 on success, -1 otherwise
Definition at line 39 of file alt_up_pci_sdma.c.
References alt_up_pci_sdma_clear(), sdma::bus_addr, sdma::data_width_in_bytes, sdma::dma_data_bit_mask, alt_up_dma_ctrller::id, alt_up_dma_ctrller::pci_dev, alt_up_dma_ctrller::private_data, SDMA_BUF_SIZE, and sdma::virt_addr.
Referenced by alt_up_pci_dev_init().
static int alt_up_pci_sdma_interrupt (struct alt_up_dma_ctrller * myctrller) [static]
The function to use interrupt.
This function implements interrupt method to check whether the DMA transfer finish. It will go to sleep until the interrupt handler wake up the process.
Parameters:
[in] myctrller The DMA controller selected
Definition at line 305 of file alt_up_pci_sdma.c.
References alt_up_dma_ctrller::condition, alt_up_dma_ctrller::irq, and alt_up_dma_ctrller::wait_queue.
Referenced by alt_up_pci_sdma_go().
static int alt_up_pci_sdma_polling (struct alt_up_dma_ctrller * myctrller) [static]
The function to poll the result.
This function implements polling method to check whether the DMA transfer finish. It will keep polling the DONE bit of the status register of DMA controller.
Parameters:
[in] myctrller The DMA controller selected
Definition at line 281 of file alt_up_pci_sdma.c.
References alt_up_dma_ctrller::dma_ctrl_base_addr, and SDMA_POLLING_TIME_OUT_CYCLES.
Referenced by alt_up_pci_sdma_go().
static void alt_up_pci_sdma_set (struct alt_up_dma_ctrller * myctrller, u32 local_addr, u32 phys_addr, u32 length, int to_device) [inline, static]
The function to set the DMA controller.
The function will write to the control register of DMA controller. It is important that you should add the pcie_tx_base_addr to the phys_addr to make sure the PCIe IP core works correctly.
Parameters:
[in] myctrller The DMA controller selected
[in] phys_addr The physical address of the kernel buffer
[in] local_addr The avalon master address you want the DMA controller read from/write to
[in] length Length of data to transfer in bytes
[in] to_device if 1, transfer from PC to device; if 0, from device to PC
Remarks:
The dynamical translation table is not supported yet, you will have to change this function to make the driver support it.
Definition at line 250 of file alt_up_pci_sdma.c.
References alt_up_dma_ctrller::dma_ctrl_base_addr, and alt_up_dma_ctrller::pcie_tx_base_addr.
Referenced by alt_up_pci_sdma_go().
void alt_up_pci_sdma_swreset (struct alt_up_dma_ctrller * myctrller) [inline]
The function to do the software reset.
This function will software reset the DMA controller. You should use this function when the DMA transfer is stall, and no other method can be used.
Parameters:
[in] myctrller The DMA controller selected
Definition at line 229 of file alt_up_pci_sdma.c.
References alt_up_dma_ctrller::dma_ctrl_base_addr.
Referenced by alt_up_pci_sdma_go().