alt_up_driver_codes: alt_up_pci_sgdma.h File Reference
alt_up_pci_sgdma.h File Reference
The header file for the Scatter-Gather DMA controller.
#include "alt_up_pci_dma.h"
Classes
struct sg_descriptor
descriptor for SG-DMA
struct sgdma
the structure to save the private data for the sgdma
Defines
#define SGDMA_BUF_SIZE 4096
The size of buffer for SG-DMA.
#define SGDMA_POLLING_TIME_OUT_CYCLES 100000
The number of cycles of checking repeated to cause a time out in polling mode.
#define SGDMA_DESCS_SIZE 4096
The size of memory allocated to save the decriptors for SG-DMA.
#define MAX_NUM_DESCS (SGDMA_DESCS_SIZE/(sizeof(sg_descriptor)))
The maximum number of decriptors supported.
Enumerations
enum desc_control_bits { DESC_CTL_GENERATE_EOP = 1 << 0, DESC_CTL_READ_FIXED_ADDR = 1 << 1, DESC_CTL_WRITE_FIXED_ADDR = 1 << 2, DESC_CTL_OWNED_BY_HW = 1 << 7 }
bit mask for descriptor
enum sgdma_register_map { SGDMA_REG_MAP_STATUS = 0x0, SGDMA_REG_MAP_CONTROL = 0x10, SGDMA_REG_MAP_NEXT_DESC = 0x20 }
Offset for registers.
enum sgdma_status_bits {
SGDMA_STATUS_ERROR = 1 << 0, SGDMA_STATUS_EOP_ENCOUNTERED = 1 << 1, SGDMA_STATUS_DESC_COMPLETED = 1 << 2, SGDMA_STATUS_CHAIN_COMPLETED = 1 << 3,
SGDMA_STATUS_BUSY = 1 << 4
}
Bit mask for status register.
enum sgdma_control_bits {
SGDMA_CTL_IE_ERROR = 1 << 0, SGDMA_CTL_IE_EOP = 1 << 1, SGDMA_CTL_IE_DESC = 1 << 2, SGDMA_CTL_IE_CHAIN = 1 << 3,
SGDMA_CTL_IE_GLOBAL = 1 << 4, SGDMA_CTL_RUN = 1 << 5, SGDMA_CTL_STOP_ER = 1 << 6, SGDMA_IE_MAX_DESC = 1 << 7,
SGDMA_CTL_SW_RESET = 1 << 16, SGDMA_CTL_PARK = 1 << 17, SGDMA_CTL_DESC_POLL_EN = 1 << 18, SGDMA_CTL_CLEAR_INTR = 1 << 31
}
Bit mask for control register.
Functions
int alt_up_pci_sgdma_init (struct alt_up_dma_ctrller *myctrller)
The function to initialize the DMA controller.
void alt_up_pci_sgdma_exit (struct alt_up_dma_ctrller *myctrller)
The function is called when the DMA controller is no longer used.
int alt_up_pci_sgdma_go (struct alt_up_dma_ctrller *myctrller, int use_interrupt)
The function to set go for DMA transfers.
void alt_up_pci_sgdma_swreset (struct alt_up_dma_ctrller *myctrller)
The function to do the software reset.
Detailed Description
The header file for the Scatter-Gather DMA controller.
This file defines parameters and the functions for SG-DMA. You can change this file and alt_up_pci_sdma.c to improve the performance of the DMA controller.
Definition in file alt_up_pci_sgdma.h.
Function Documentation
void alt_up_pci_sgdma_exit (struct alt_up_dma_ctrller * myctrller)
The function is called when the DMA controller is no longer used.
This function will free all the memory allocated in alt_up_pci_sgdma_init(). The function is called in alt_up_pci_dev_exit().
Parameters:
[in] myctrller The DMA controller selected
Definition at line 77 of file alt_up_pci_sgdma.c.
References sgdma::bus_addr, sgdma::descriptors, sgdma::descriptors_bus, alt_up_dma_ctrller::pci_dev, alt_up_dma_ctrller::private_data, SGDMA_BUF_SIZE, SGDMA_DESCS_SIZE, and sgdma::virt_addr.
Referenced by alt_up_pci_dev_exit().
int alt_up_pci_sgdma_go (struct alt_up_dma_ctrller * myctrller, int use_interrupt)
The function to set go for DMA transfers.
This function will do all the transcations in the dma_queue. If the transfer size is larger than the SDMA_BUF_SIZE, it will automatically divide the transfer into multiple tranfers.
Parameters:
[in] myctrller The DMA controller selected
[in] use_interrupt if 1, set the DMA controller to assert irq signal
Returns:
Returns 0 on success, -1 otherwise
Definition at line 97 of file alt_up_pci_sgdma.c.
References alt_up_pci_sgdma_clear(), alt_up_pci_sgdma_interrupt(), alt_up_pci_sgdma_polling(), alt_up_pci_sgdma_setdesc(), alt_up_pci_sgdma_swreset(), sgdma::bus_addr, sgdma::descriptors_bus, alt_up_dma_ctrller::dma_ctrl_base_addr, alt_up_dma_ctrller::dma_queue, alt_up_pci_dma::dma_rw_slave_addr, alt_up_pci_dma::length, alt_up_dma_ctrller::pcie_tx_base_addr, alt_up_dma_ctrller::private_data, alt_up_dma_ctrller::queue_end, SGDMA_BUF_SIZE, alt_up_pci_dma::to_device, alt_up_pci_dma::user_buffer_addr, and sgdma::virt_addr.
Referenced by alt_up_pci_ioctl().
int alt_up_pci_sgdma_init (struct alt_up_dma_ctrller * myctrller)
The function to initialize the DMA controller.
This function allocates buffer for the SG-DMA controller to transfer data, initialize necessary data, and clear the registers for dma controller.
Parameters:
[in] myctrller pointer to struct alt_up_dma_ctrller which points to the dma controller needed to be initialized
Returns:
Returns 0 on success, -1 otherwise
Definition at line 37 of file alt_up_pci_sgdma.c.
References alt_up_pci_sgdma_clear(), sgdma::bus_addr, sgdma::descriptors, sgdma::descriptors_bus, alt_up_dma_ctrller::id, alt_up_dma_ctrller::pci_dev, alt_up_dma_ctrller::private_data, SGDMA_BUF_SIZE, SGDMA_DESCS_SIZE, and sgdma::virt_addr.
Referenced by alt_up_pci_dev_init().
void alt_up_pci_sgdma_swreset (struct alt_up_dma_ctrller * myctrller) [inline]
The function to do the software reset.
This function will software reset the DMA controller. You should use this function when the DMA transfer is stall, and no other method can be used.
Parameters:
[in] myctrller The DMA controller selected
Definition at line 209 of file alt_up_pci_sgdma.c.
References alt_up_dma_ctrller::dma_ctrl_base_addr.
Referenced by alt_up_pci_sgdma_go().