alt_up_driver_codes: alt_up_pci_sdma.h File Reference
alt_up_pci_sdma.h File Reference
The header file for the simple DMA controller.
#include "alt_up_pci_dma.h"
Classes
struct sdma
The structure to save the private data for the sdma.
Defines
#define SDMA_BUF_SIZE 4096
The size of the buffer allocated for the DMA transfer.
#define SDMA_POLLING_TIME_OUT_CYCLES 100000
The number of cycles of checking repeated to cause a time out in polling mode.
Enumerations
enum dma_register_map {
DMA_REG_MAP_STATUS = 0x0, DMA_REG_MAP_RD_ADDR = 0x4, DMA_REG_MAP_WT_ADDR = 0x8, DMA_REG_MAP_LEN = 0xC,
DMA_REG_MAP_CONTROL = 0x18
}
Offset of registers of the DMA controller.
enum dma_status_bits { DMA_STATUS_DONE = 1 << 0, DMA_STATUS_BUSY = 1 << 1, DMA_STATUS_LEN = 1 << 4 }
Bit mask for status registers.
enum dma_control_bits {
DMA_CTL_BIT_BYTE = 1 << 0, DMA_CTL_BIT_HW = 1 << 1, DMA_CTL_BIT_WORD = 1 << 2, DMA_CTL_BIT_GO = 1 << 3,
DMA_CTL_BIT_I_EN = 1 << 4, DMA_CTL_BIT_LEEN = 1 << 7, DMA_CTL_BIT_DOUBLEWORD = 1 << 10, DMA_CTL_BIT_QUADWORD = 1 << 11,
DMA_CTL_BIT_SOFTWARERESET = 1 << 12
}
Bit mask for control registers.
Functions
int alt_up_pci_sdma_init (struct alt_up_dma_ctrller *myctrller, int transfer_data_width)
The function to initialize the DMA controller.
void alt_up_pci_sdma_exit (struct alt_up_dma_ctrller *myctrller)
The function is called when the DMA controller is no longer used.
int alt_up_pci_sdma_go (struct alt_up_dma_ctrller *myctrller, int use_interrupt)
The function to set go for DMA transfers.
void alt_up_pci_sdma_swreset (struct alt_up_dma_ctrller *myctrller)
The function to do the software reset.
Detailed Description
The header file for the simple DMA controller.
This file defines parameters and functions for the DMA controllers. You can change this file and alt_up_pci_sdma.c to improve the performance of the DMA controller.
Definition in file alt_up_pci_sdma.h.
Function Documentation
void alt_up_pci_sdma_exit (struct alt_up_dma_ctrller * myctrller)
The function is called when the DMA controller is no longer used.
This function will free all the memory allocated in alt_up_pci_sdma_init(). The function is called in alt_up_pci_dev_exit().
Parameters:
[in] myctrller The DMA controller selected
Definition at line 87 of file alt_up_pci_sdma.c.
References sdma::bus_addr, alt_up_dma_ctrller::pci_dev, alt_up_dma_ctrller::private_data, SDMA_BUF_SIZE, and sdma::virt_addr.
Referenced by alt_up_pci_dev_exit().
int alt_up_pci_sdma_go (struct alt_up_dma_ctrller * myctrller, int use_interrupt)
The function to set go for DMA transfers.
This function will do all the transcations in the dma_queue. If the transfer size is larger than the SDMA_BUF_SIZE, it will automatically divide the transfer into multiple tranfers.
Parameters:
[in] myctrller The DMA controller selected
[in] use_interrupt if 1, set the DMA controller to assert irq signal
Returns:
Returns 0 on success, -1 otherwise
Definition at line 106 of file alt_up_pci_sdma.c.
References alt_up_pci_sdma_clear(), alt_up_pci_sdma_interrupt(), alt_up_pci_sdma_polling(), alt_up_pci_sdma_set(), alt_up_pci_sdma_swreset(), sdma::bus_addr, sdma::data_width_in_bytes, alt_up_dma_ctrller::dma_ctrl_base_addr, sdma::dma_data_bit_mask, alt_up_dma_ctrller::dma_queue, alt_up_pci_dma::dma_rw_slave_addr, alt_up_pci_dma::length, alt_up_dma_ctrller::private_data, alt_up_dma_ctrller::queue_end, SDMA_BUF_SIZE, alt_up_pci_dma::to_device, alt_up_pci_dma::user_buffer_addr, and sdma::virt_addr.
Referenced by alt_up_pci_ioctl().
int alt_up_pci_sdma_init (struct alt_up_dma_ctrller * myctrller, int transfer_data_width)
The function to initialize the DMA controller.
This function allocates buffer for the DMA controller to transfer data, initialize necessary data, and clear the registers for dma controller.
Parameters:
[in] myctrller pointer to struct alt_up_dma_ctrller which points to the dma controller needed to be initialized
[in] transfer_data_width data width setting for the dma controller
Returns:
Returns 0 on success, -1 otherwise
Definition at line 39 of file alt_up_pci_sdma.c.
References alt_up_pci_sdma_clear(), sdma::bus_addr, sdma::data_width_in_bytes, sdma::dma_data_bit_mask, alt_up_dma_ctrller::id, alt_up_dma_ctrller::pci_dev, alt_up_dma_ctrller::private_data, SDMA_BUF_SIZE, and sdma::virt_addr.
Referenced by alt_up_pci_dev_init().
void alt_up_pci_sdma_swreset (struct alt_up_dma_ctrller * myctrller) [inline]
The function to do the software reset.
This function will software reset the DMA controller. You should use this function when the DMA transfer is stall, and no other method can be used.
Parameters:
[in] myctrller The DMA controller selected
Definition at line 229 of file alt_up_pci_sdma.c.
References alt_up_dma_ctrller::dma_ctrl_base_addr.
Referenced by alt_up_pci_sdma_go().