alt_up_driver_codes: alt_up_pci_driver.c File Reference
alt_up_pci_driver.c File Reference
The source file contains all the functions defined in alt_up_pci_driver.h.
#include "alt_up_pci_driver.h"
#include "alt_up_pci_ioctl.h"
Functions
static int __init alt_up_pci_init (void)
static void __exit alt_up_pci_exit (void)
static int __devinit alt_up_pci_probe (struct pci_dev *dev, const struct pci_device_id *id)
static void __devexit alt_up_pci_remove (struct pci_dev *dev)
static int alt_up_pci_open (struct inode *inode, struct file *filp)
static int alt_up_pci_release (struct inode *inode, struct file *filp)
static ssize_t alt_up_pci_write (struct file *filp, const char __user *buf, size_t count, loff_t *f_pos)
static ssize_t alt_up_pci_read (struct file *filp, char __user *buf, size_t count, loff_t *f_pos)
static loff_t alt_up_pci_llseek (struct file *filp, loff_t off, int whence)
static int alt_up_pci_ioctl (struct inode *inode, struct file *filp, unsigned int cmd, unsigned long arg)
static int alt_up_pci_dev_init (struct alt_up_pci_dev *mydev)
static void alt_up_pci_dev_exit (struct alt_up_pci_dev *mydev)
static irqreturn_t alt_up_pci_irqhandler (int irq, void *dev_id)
Detailed Description
The source file contains all the functions defined in alt_up_pci_driver.h.
Definition in file alt_up_pci_driver.c.
Function Documentation
static void alt_up_pci_dev_exit (struct alt_up_pci_dev * mydev) [static]
This function will call the cleanup function for DMAs to undo everything in alt_up_pci_dev_init().
Parameters:
[in] mydev
Definition at line 635 of file alt_up_pci_driver.c.
References alt_up_pci_sdma_exit(), alt_up_pci_sgdma_exit(), alt_up_pci_dev::controllers, and alt_up_dma_ctrller::type.
Referenced by alt_up_pci_probe(), and alt_up_pci_remove().
static int alt_up_pci_dev_init (struct alt_up_pci_dev * mydev) [static]
This function will initialize the components in the struct alt_up_pci_dev.
Parameters:
[in] mydev
Returns:
Return 0 on success, -1 otherwise.
Definition at line 573 of file alt_up_pci_driver.c.
References alt_up_pci_sdma_init(), alt_up_pci_sgdma_init(), alt_up_pci_dev::bar, alt_up_dma_ctrller::condition, alt_up_pci_dev::controllers, dma_ctrl_bar_no, dma_ctrl_base_addr, alt_up_dma_ctrller::dma_ctrl_base_addr, dma_irq_no, dma_type, DRV_NAME, alt_up_dma_ctrller::id, alt_up_dma_ctrller::irq, alt_up_pci_dev::pci_dev, alt_up_dma_ctrller::pci_dev, pcie_cra_bar_no, pcie_cra_base_addr, alt_up_dma_ctrller::pcie_cra_base_addr, alt_up_dma_ctrller::pcie_tx_base_addr, alt_up_dma_ctrller::queue_end, alt_up_pci_dev::rw_bar_no, sdma_data_width, tx_base_addr, alt_up_dma_ctrller::type, and alt_up_dma_ctrller::wait_queue.
Referenced by alt_up_pci_probe().
static void __exit alt_up_pci_exit (void) [static]
This function is only called once, when the module is removed from the kernel. It will unregister the alt_up_pci_driver (struct pci_driver).
Definition at line 41 of file alt_up_pci_driver.c.
References alt_up_pci_driver, and DRV_NAME.
static int __init alt_up_pci_init (void) [static]
This function is only called once, when the module in loaded into the kernel. It will set the first entry of the pci_id_table to make the driver support vendor_id and device_id set by the config_file (or 0x1172 and 0x0de4 by default). Then, register the alt_up_pci_driver (struct pci_driver).
Returns:
Returns 0 on success.
Remarks:
The current driver only support one set of vendor and device IDs. Changes need to be made to support multi-type of devices
Definition at line 23 of file alt_up_pci_driver.c.
References alt_up_pci_driver, alt_up_pci_id_table, device_id, DRV_NAME, and vendor_id.
static int alt_up_pci_ioctl (struct inode * inode, struct file * filp, unsigned int cmd, unsigned long arg) [static]
This function will first copy the alt_up_ioctl_arg to the kernel, and then execute the command accordingly. There are two commands are related to DMA : ALT_UP_IOCTL_DMA_ADD, and ALT_UP_IOCTL_DMA_GO. The DMA related structures and functions are defined in alt_up_pci_dma.h, alt_up_pci_sdma.h, and alt_up_pci_sgdma.h. The struct alt_up_ioctl_arg and the commands are defined in file alt_up_pci_ioctl.h.
Parameters:
[in] inode
[in] filp
[in] cmd The command of the ioctl command
[in] arg The pointer to the structure alt_up_ioctl_arg in the user space
Returns:
Return 0 on success
Remarks:
The function provides the ability to perform various types hardware control in addition to read and write the device. Adding new command needs to change the file alt_up_pci_ioctl.h and this function accordingly.
Definition at line 466 of file alt_up_pci_driver.c.
References ALT_UP_IOCTL_DMA_ADD, ALT_UP_IOCTL_DMA_GO, ALT_UP_IOCTL_SET_BAR, alt_up_pci_sdma_go(), alt_up_pci_sgdma_go(), alt_up_pci_dev::bar, alt_up_pci_dev::controllers, DMA_MAX_QUEUE_NUM, MAX_NUM_OF_BARS, MAX_NUM_OF_DMAS, and alt_up_pci_dev::rw_bar_no.
static irqreturn_t alt_up_pci_irqhandler (int irq, void * dev_id) [static]
This function will check which DMA controller causes the interrupt and then wake up all the waiting processes on the wait_queue of that DMA controller.
Parameters:
[in] irq
[in] dev_id
Returns:
Return IRQ_HANDLED if the interrupt is handled, otherwise return IRQ_NONE.
Definition at line 662 of file alt_up_pci_driver.c.
References alt_up_pci_dev::bar, alt_up_dma_ctrller::condition, alt_up_pci_dev::controllers, alt_up_dma_ctrller::irq, pcie_cra_bar_no, pcie_cra_base_addr, and alt_up_dma_ctrller::wait_queue.
Referenced by alt_up_pci_probe().
static loff_t alt_up_pci_llseek (struct file * filp, loff_t off, int whence) [static]
This function is usually used along with read/write to set the proper offset addr for them.
Parameters:
[in] filp
[in] off The offset
[in] whence The starting position for the offset
Returns:
Return the new file position on success.
Definition at line 424 of file alt_up_pci_driver.c.
static int alt_up_pci_open (struct inode * inode, struct file * filp) [static]
This function is called when the user application try to use the driver (by opening a file). It retrieve the pointer to struct alt_up_pci_dev from the struct inode, and save it into struct struct file to make the following file operations easier.
Parameters:
[in] inode
[in] filp
Returns:
Return 0 on success
Remarks:
The current driver do not support multiple opening files. This function needs to be enhanced if supporting multiple opening files
Definition at line 250 of file alt_up_pci_driver.c.
References alt_up_pci_dev::cdev.
static int __devinit alt_up_pci_probe (struct pci_dev * dev, const struct pci_device_id * id) [static]
This function is called by the PCI core when it has a struct pci_dev that it thinks the driver wants to control. It will allocate the memory for the struct alt_up_pci_dev, initialize it correctly and dynamically allocate a character device node.
Parameters:
[in] dev The pointer to the pci device that evokes the probe function.
[in] id The pci_id_table of the driver.
Returns:
Return 0 on success.
Definition at line 60 of file alt_up_pci_driver.c.
References alt_up_pci_dev_exit(), alt_up_pci_dev_init(), alt_up_pci_fops, alt_up_pci_irqhandler(), DRV_NAME, and pci_dma_bit_range.
static ssize_t alt_up_pci_read (struct file * filp, char __user * buf, size_t count, loff_t * f_pos) [static]
This function is called when the user application try to read from the file (by using read(fd, buf, count)). It will read "count" bytes from the "mydev->rw_bar_no" bar with a offset "*f_pos". If the count is multiple of 4, it will use ioread32(), otherwise ioread8(). The performance of this function is slow, so it is intended for small size data transfer.
Parameters:
[in] filp
[in] buf The pointer to the user buffer
[in] count The number of data in bytes needed to be read
[in] f_pos The current file position
Returns:
Return the number of bytes written on success, -1 otherwise
Definition at line 360 of file alt_up_pci_driver.c.
References alt_up_pci_dev::bar, alt_up_pci_dev::bar_size, and alt_up_pci_dev::rw_bar_no.
static int alt_up_pci_release (struct inode * inode, struct file * filp) [static]
This function is called when the user application try to close the driver (by closing a file). It should undo everything in alt_up_pci_open().
Parameters:
[in] inode
[in] filp
Returns:
Return 0 on success
Remarks:
The current driver do not support multiple opening files. This function needs to be enhanced if supporting multiple opening files
Definition at line 273 of file alt_up_pci_driver.c.
static void __devexit alt_up_pci_remove (struct pci_dev * dev) [static]
This function is called by the PCI core when the struct pci_dev is being removed from the system or the PCI driver is being unloaded from the kernel. It will undo everything in alt_up_pci_probe()
Parameters:
[in] dev The pointer to the pci device evoke the function
Definition at line 218 of file alt_up_pci_driver.c.
References alt_up_pci_dev_exit(), alt_up_pci_dev::cdev, alt_up_pci_dev::cdev_no, and alt_up_pci_dev::irq_line.
static ssize_t alt_up_pci_write (struct file * filp, const char __user * buf, size_t count, loff_t * f_pos) [static]
This function is called when the user application try to write to the file (by using write(fd, buf, count)). It will write "count" bytes to the "mydev->rw_bar_no" bar with a offset "*f_pos". If the count is multiple of 4, it will use iowrite32(), otherwise iowrite8(). The performance of this function is slow, so it is intended for small size data transfer.
Parameters:
[in] filp
[in] buf The pointer to the user buffer
[in] count The number of data in bytes needed to write
[in] f_pos The current file position
Returns:
Return the number of bytes written on success, -1 otherwise
Definition at line 292 of file alt_up_pci_driver.c.
References alt_up_pci_dev::bar, alt_up_pci_dev::bar_size, and alt_up_pci_dev::rw_bar_no.